using Rpg.Presentation.Battle.Actions;
using Rpg.Domain.Battle.Grid;
using Rpg.Presentation.Battle;
using Rpg.Presentation.Battle.Entities;
using Rpg.Presentation.Battle.Debug;
using Rpg.Presentation.Battle.Feedback;
using Rpg.Presentation.Battle.Flow;
using Rpg.Presentation.Battle.Preview;
using Rpg.Presentation.Common;
using Rpg.Presentation.World;
using Rpg.Definitions.Battle.Abilities;
using Rpg.Definitions.Battle.Audio;
using Rpg.Application.Battle;
using Rpg.Application.World;
using Rpg.Definitions.World;
using Rpg.Domain.World;
using System.Text.Json;

Environment.SetEnvironmentVariable("RPG_GAMELOG_DIR", Path.Combine(Path.GetTempPath(), "rpg-test-logs"));

BattleHitFeedbackRegressionCases.Run("multi-target hit feedback outlines every target and formats damage numbers", BattleHitFeedbackRegressionCases.MultiTargetHitFeedback);
BattleHitFeedbackRegressionCases.Run("damage number starts close to target and drifts lightly right upward", BattleHitFeedbackRegressionCases.DamageNumberMotionDefaults);
BattleHitFeedbackRegressionCases.Run("friendly hover uses green movement and yellow attack preview kinds", BattleHitFeedbackRegressionCases.FriendlyHoverStyle);
BattleHitFeedbackRegressionCases.Run("friendly hover keeps combined post-move attack preview", BattleHitFeedbackRegressionCases.FriendlyHoverWorkload);
BattleHitFeedbackRegressionCases.Run("friendly hover suppresses yellow attack cells under target units", BattleHitFeedbackRegressionCases.FriendlyHoverSuppressesAttackCellsUnderTargets);
BattleHitFeedbackRegressionCases.Run("hover frame uses unit footprint", BattleHitFeedbackRegressionCases.HoverFrameUsesUnitFootprint);
BattleHitFeedbackRegressionCases.Run("highlight tile layer updates only changed cells", BattleHitFeedbackRegressionCases.HighlightTileLayerDiff);
BattleHitFeedbackRegressionCases.Run("attack target presentation outlines units instead of target cells", BattleHitFeedbackRegressionCases.AttackTargetPresentation);
BattleHitFeedbackRegressionCases.Run("movement path arrows are disabled by default", BattleHitFeedbackRegressionCases.MovementPathArrowsDisabled);
BattleHitFeedbackRegressionCases.Run("unit visual scale uses global and footprint tuning multipliers", BattleHitFeedbackRegressionCases.UnitVisualScaleMultiplier);
BattleHitFeedbackRegressionCases.Run("unit definitions expose 1x1 footprint defaults", BattleHitFeedbackRegressionCases.UnitDefinitionFootprintDefaults);
BattleHitFeedbackRegressionCases.Run("battle unit factory scales sprites uniformly by footprint", BattleHitFeedbackRegressionCases.BattleUnitFactoryScalesSpritesUniformlyByFootprint);
BattleHitFeedbackRegressionCases.Run("world site runtime copies definition footprint to battle requests", BattleHitFeedbackRegressionCases.WorldSiteRuntimeCopiesDefinitionFootprintToBattleRequests);
BattleHitFeedbackRegressionCases.Run("action cue waits before action and hides afterward", BattleHitFeedbackRegressionCases.ActionCueSequencerOrder);
BattleHitFeedbackRegressionCases.Run("hover info panel anchors to screen edge instead of mouse", BattleHitFeedbackRegressionCases.HoverInfoPanelAnchorsToScreenEdge);
BattleHitFeedbackRegressionCases.Run("map camera middle drag pans opposite to mouse motion", BattleHitFeedbackRegressionCases.MapCameraMiddleDragPansOppositeToMouseMotion);
BattleHitFeedbackRegressionCases.Run("unit audio definition resolves cue variants deterministically", BattleHitFeedbackRegressionCases.UnitAudioDefinitionResolvesCueVariants);
BattleHitFeedbackRegressionCases.Run("ability spatial contract defaults to unit target eight way single actor", BattleHitFeedbackRegressionCases.AbilitySpatialContractDefaults);
BattleHitFeedbackRegressionCases.Run("battle unit base scene authors interaction collision shape", BattleHitFeedbackRegressionCases.BattleUnitBaseSceneAuthorsInteractionCollisionShape);
BattleHitFeedbackRegressionCases.Run("battle unit preview workbench mirrors visual resources", BattleHitFeedbackRegressionCases.BattleUnitPreviewWorkbenchIsVisualResourceMirror);
BattleHitFeedbackRegressionCases.Run("starter battle unit definitions reference audio profiles", BattleHitFeedbackRegressionCases.StarterUnitDefinitionsReferenceAudioProfiles);
BattleHitFeedbackRegressionCases.Run("legacy starter unit packages are removed", BattleHitFeedbackRegressionCases.LegacyStarterUnitPackagesAreRemoved);
BattleHitFeedbackRegressionCases.Run("starter audio migration is mapped from source visuals", BattleHitFeedbackRegressionCases.StarterAudioMigrationUsesSourceVisuals);
BattleHitFeedbackRegressionCases.Run("battle unit display names use resource label plus two digit instance index", BattleHitFeedbackRegressionCases.BattleUnitDisplayNamesUseIndexedResourceLabel);
BattleHitFeedbackRegressionCases.Run("starter unit display names use source visual translations", BattleHitFeedbackRegressionCases.StarterUnitDisplayNamesUseSourceVisualTranslations);
BattleHitFeedbackRegressionCases.Run("world unit labels resolve through battle unit definitions", BattleHitFeedbackRegressionCases.WorldUnitLabelsResolveThroughBattleDefinitions);
BattleHitFeedbackRegressionCases.Run("world resource and faction labels resolve through strategic definitions", BattleHitFeedbackRegressionCases.WorldResourceAndFactionLabelsResolveThroughDefinitions);
BattleHitFeedbackRegressionCases.Run("world site and facility labels resolve through strategic definitions", BattleHitFeedbackRegressionCases.WorldSiteAndFacilityLabelsResolveThroughDefinitions);
BattleHitFeedbackRegressionCases.Run("world action resource text uses custom resource display names", BattleHitFeedbackRegressionCases.WorldActionResourceTextUsesCustomDisplayNames);
BattleHitFeedbackRegressionCases.Run("world action site and facility preview text uses custom display names", BattleHitFeedbackRegressionCases.WorldActionSiteAndFacilityPreviewTextUsesCustomDisplayNames);
BattleHitFeedbackRegressionCases.Run("world site hover summary uses local resources and force counts", BattleHitFeedbackRegressionCases.WorldSiteHoverSummaryUsesLocalResourcesAndForceCounts);
BattleHitFeedbackRegressionCases.Run("world site hover summary stays inside viewport", BattleHitFeedbackRegressionCases.WorldSiteHoverSummaryStaysInsideViewport);
BattleHitFeedbackRegressionCases.Run("strategic world forwards middle mouse camera navigation", BattleHitFeedbackRegressionCases.StrategicWorldForwardsMiddleMouseCameraNavigation);
BattleHitFeedbackRegressionCases.Run("strategic world resets camera navigation input on scene entry", BattleHitFeedbackRegressionCases.StrategicWorldResetsCameraNavigationInputOnSceneEntry);
BattleHitFeedbackRegressionCases.Run("map camera ignores stale move press events after scene reset", BattleHitFeedbackRegressionCases.MapCameraIgnoresStaleMovePressEventsAfterSceneReset);
BattleHitFeedbackRegressionCases.Run("battle result applier messages use configured display names", BattleHitFeedbackRegressionCases.BattleResultApplierMessagesUseConfiguredDisplayNames);
BattleHitFeedbackRegressionCases.Run("battle unit factory keeps definition caches shared across scenes", BattleHitFeedbackRegressionCases.BattleUnitFactoryKeepsDefinitionCachesShared);
BattleHitFeedbackRegressionCases.Run("battle runtime playback consumes runtime movement cells", BattleHitFeedbackRegressionCases.BattleRuntimePlaybackConsumesRuntimeMovementCells);
BattleHitFeedbackRegressionCases.Run("battle runtime playback keeps move loop across consecutive move steps", BattleHitFeedbackRegressionCases.BattleRuntimePlaybackKeepsMoveLoopAcrossConsecutiveMoveSteps);
BattleHitFeedbackRegressionCases.Run("battle runtime playback waits for attack animation duration", BattleHitFeedbackRegressionCases.BattleRuntimePlaybackWaitsForAttackAnimationDuration);
BattleHitFeedbackRegressionCases.Run("battle runtime live observation uses tick clock", BattleHitFeedbackRegressionCases.BattleRuntimeLiveObservationUsesTickClock);
BattleHitFeedbackRegressionCases.Run("battle runtime playback does not globally gate movement on attack animation", BattleHitFeedbackRegressionCases.BattleRuntimePlaybackDoesNotGloballyGateMovementOnAttackAnimation);
BattleHitFeedbackRegressionCases.Run("battle runtime playback plans move idle only at sequence boundary", BattleHitFeedbackRegressionCases.BattleRuntimePlaybackPlansMoveIdleOnlyAtSequenceBoundary);
BattleHitFeedbackRegressionCases.Run("battle runtime live movement uses actor motion lane", BattleHitFeedbackRegressionCases.BattleRuntimeLiveMovementUsesActorMotionLane);
BattleHitFeedbackRegressionCases.Run("battle runtime live movement queues before actor visual tail waits", BattleHitFeedbackRegressionCases.BattleRuntimeLiveMovementQueuesBeforeActorVisualTailWaits);
BattleHitFeedbackRegressionCases.Run("battle runtime visual movement keeps runtime action duration", BattleHitFeedbackRegressionCases.BattleRuntimeVisualMovementKeepsRuntimeActionDuration);
BattleHitFeedbackRegressionCases.Run("battle presentation timeline separates movement completion from action backlog", BattleHitFeedbackRegressionCases.BattlePresentationTimelineSeparatesMovementCompletionFromActionBacklog);
BattleHitFeedbackRegressionCases.Run("battle presentation timeline waits target movement but not target attack backlog", BattleHitFeedbackRegressionCases.BattlePresentationTimelineWaitsTargetMovementButNotTargetAttackBacklog);
BattleHitFeedbackRegressionCases.Run("battle runtime registers Godot performance monitors", BattleHitFeedbackRegressionCases.BattleRuntimeRegistersGodotPerformanceMonitors);
BattleHitFeedbackRegressionCases.Run("battle runtime playback delays damage until same tick target movement settles", BattleHitFeedbackRegressionCases.BattleRuntimePlaybackDelaysDamageUntilSameTickTargetMovementSettles);
BattleHitFeedbackRegressionCases.Run("battle runtime live observation waits for same tick movement before dependent attack", BattleHitFeedbackRegressionCases.BattleRuntimeLiveObservationWaitsForSameTickMovementBeforeDependentAttack);
BattleHitFeedbackRegressionCases.Run("runtime playback damage waits for target movement but not target attack backlog", BattleHitFeedbackRegressionCases.RuntimePlaybackDamageWaitsForTargetMovementButNotTargetAttackBacklog);
BattleHitFeedbackRegressionCases.Run("runtime playback movement path uses footprint center resolver", BattleHitFeedbackRegressionCases.RuntimePlaybackMovementPathUsesFootprintCenterResolver);
BattleHitFeedbackRegressionCases.Run("battle runtime presentation starts incremental runtime before settlement", BattleHitFeedbackRegressionCases.BattleRuntimePresentationStartsIncrementalRuntimeBeforeSettlement);
BattleHitFeedbackRegressionCases.Run("battle runtime live clock does not use lookahead batches", BattleHitFeedbackRegressionCases.BattleRuntimeLiveClockDoesNotUseLookaheadBatches);
BattleHitFeedbackRegressionCases.Run("battle runtime live observation does not await movement or attack durations", BattleHitFeedbackRegressionCases.BattleRuntimeLiveObservationDoesNotAwaitMovementOrAttackDurations);
BattleHitFeedbackRegressionCases.Run("battle runtime presentation pause waits without tree pause", BattleHitFeedbackRegressionCases.BattleRuntimePresentationPauseWaitsWithoutTreePause);
BattleHitFeedbackRegressionCases.Run("battle unit command selection uses unit outline shader", BattleHitFeedbackRegressionCases.BattleUnitCommandSelectionUsesUnitOutlineShader);
BattleHitFeedbackRegressionCases.Run("deployment zones use dedicated overlay shader", BattleHitFeedbackRegressionCases.DeploymentZonesUseDedicatedOverlayShader);
BattleHitFeedbackRegressionCases.Run("realtime damage reaction does not play hit animation", BattleHitFeedbackRegressionCases.RealtimeDamageReactionDoesNotPlayHitAnimation);
BattleHitFeedbackRegressionCases.Run("unit attack speed is bound to runtime and attack animation speed", BattleHitFeedbackRegressionCases.UnitAttackSpeedContract);
BattleHitFeedbackRegressionCases.Run("unit combat stats are bound into runtime snapshots", BattleHitFeedbackRegressionCases.UnitCombatStatsSnapshotContract);
BattleHitFeedbackRegressionCases.Run("battle unit base authors health bar and fallback animation", BattleHitFeedbackRegressionCases.BattleUnitBaseSceneAuthorsHealthBarAndFallbackAnimation);
BattleHitFeedbackRegressionCases.Run("defeated unit presentation hides health bar before fast death animation", BattleHitFeedbackRegressionCases.DefeatedUnitPresentationHidesHealthBarBeforeFastDeathAnimation);
BattleHitFeedbackRegressionCases.Run("limbo ai battle decision tree mirrors enemy greedy branches", BattleHitFeedbackRegressionCases.LimboAiBattleDecisionTreeMirrorsEnemyGreedyBranches);
BattleHitFeedbackRegressionCases.Run("limbo ai battle decision tree mirrors allied command branches", BattleHitFeedbackRegressionCases.LimboAiBattleDecisionTreeMirrorsAlliedCommandBranches);
BattleHitFeedbackRegressionCases.Run("limbo ai battle resource boundary is authored", BattleHitFeedbackRegressionCases.LimboAiBattleResourceBoundaryIsAuthored);
BattleHitFeedbackRegressionCases.Run("limbo ai battle facade writes blackboard and emits intent", BattleHitFeedbackRegressionCases.LimboAiBattleFacadeWritesBlackboardAndEmitsIntent);
BattleHitFeedbackRegressionCases.Run("limbo ai battle tasks pass blackboard through facade", BattleHitFeedbackRegressionCases.LimboAiBattleTasksPassBlackboardThroughFacade);
BattleHitFeedbackRegressionCases.Run("limbo ai authored resources mirror planner branches", BattleHitFeedbackRegressionCases.LimboAiAuthoredResourcesMirrorPlannerBranches);
BattleHitFeedbackRegressionCases.Run("limbo ai godot facade requires blackboard target before strike", BattleHitFeedbackRegressionCases.LimboAiGodotFacadeRequiresBlackboardTargetBeforeStrike);
BattleHitFeedbackRegressionCases.Run("battle result applier uses survivor counts when garrisoning assault army", BattleHitFeedbackRegressionCases.BattleResultApplierUsesSurvivorCountsWhenGarrisoningAssaultArmy);
BattleHitFeedbackRegressionCases.Run("unit display name translation report keeps low confidence review queue bounded", BattleHitFeedbackRegressionCases.UnitDisplayNameTranslationReportQuality);
