using Rpg.Presentation.Battle.Actions;
using Rpg.Domain.Battle.Grid;
using Rpg.Presentation.Battle;
using Rpg.Presentation.Battle.Entities;
using Rpg.Presentation.Battle.Debug;
using Rpg.Presentation.Battle.Feedback;
using Rpg.Presentation.Battle.Flow;
using Rpg.Presentation.Battle.Preview;
using Rpg.Presentation.Common;
using Rpg.Presentation.World;
using Rpg.Definitions.Battle.Audio;
using Rpg.Application.Battle;
using Rpg.Application.World;
using Rpg.Definitions.World;
using Rpg.Domain.World;
using System.Text.Json;

Environment.SetEnvironmentVariable("RPG_GAMELOG_DIR", Path.Combine(Path.GetTempPath(), "rpg-test-logs"));

BattleHitFeedbackRegressionCases.Run("multi-target hit feedback outlines every target and formats damage numbers", BattleHitFeedbackRegressionCases.MultiTargetHitFeedback);
BattleHitFeedbackRegressionCases.Run("damage number starts close to target and drifts lightly right upward", BattleHitFeedbackRegressionCases.DamageNumberMotionDefaults);
BattleHitFeedbackRegressionCases.Run("friendly hover uses green movement and yellow attack preview kinds", BattleHitFeedbackRegressionCases.FriendlyHoverStyle);
BattleHitFeedbackRegressionCases.Run("friendly hover keeps combined post-move attack preview", BattleHitFeedbackRegressionCases.FriendlyHoverWorkload);
BattleHitFeedbackRegressionCases.Run("friendly hover suppresses yellow attack cells under target units", BattleHitFeedbackRegressionCases.FriendlyHoverSuppressesAttackCellsUnderTargets);
BattleHitFeedbackRegressionCases.Run("highlight tile layer updates only changed cells", BattleHitFeedbackRegressionCases.HighlightTileLayerDiff);
BattleHitFeedbackRegressionCases.Run("attack target presentation outlines units instead of target cells", BattleHitFeedbackRegressionCases.AttackTargetPresentation);
BattleHitFeedbackRegressionCases.Run("movement path arrows are disabled by default", BattleHitFeedbackRegressionCases.MovementPathArrowsDisabled);
BattleHitFeedbackRegressionCases.Run("unit visual scale uses global 0.8 multiplier", BattleHitFeedbackRegressionCases.UnitVisualScaleMultiplier);
BattleHitFeedbackRegressionCases.Run("action cue waits before action and hides afterward", BattleHitFeedbackRegressionCases.ActionCueSequencerOrder);
BattleHitFeedbackRegressionCases.Run("hover info panel anchors to screen edge instead of mouse", BattleHitFeedbackRegressionCases.HoverInfoPanelAnchorsToScreenEdge);
BattleHitFeedbackRegressionCases.Run("map camera middle drag pans opposite to mouse motion", BattleHitFeedbackRegressionCases.MapCameraMiddleDragPansOppositeToMouseMotion);
BattleHitFeedbackRegressionCases.Run("unit audio definition resolves cue variants deterministically", BattleHitFeedbackRegressionCases.UnitAudioDefinitionResolvesCueVariants);
BattleHitFeedbackRegressionCases.Run("starter battle unit definitions reference audio profiles", BattleHitFeedbackRegressionCases.StarterUnitDefinitionsReferenceAudioProfiles);
BattleHitFeedbackRegressionCases.Run("starter audio migration is mapped from source visuals", BattleHitFeedbackRegressionCases.StarterAudioMigrationUsesSourceVisuals);
BattleHitFeedbackRegressionCases.Run("battle unit display names use resource label plus two digit instance index", BattleHitFeedbackRegressionCases.BattleUnitDisplayNamesUseIndexedResourceLabel);
BattleHitFeedbackRegressionCases.Run("starter unit display names use source visual translations", BattleHitFeedbackRegressionCases.StarterUnitDisplayNamesUseSourceVisualTranslations);
BattleHitFeedbackRegressionCases.Run("world unit labels resolve through battle unit definitions", BattleHitFeedbackRegressionCases.WorldUnitLabelsResolveThroughBattleDefinitions);
BattleHitFeedbackRegressionCases.Run("world resource and faction labels resolve through strategic definitions", BattleHitFeedbackRegressionCases.WorldResourceAndFactionLabelsResolveThroughDefinitions);
BattleHitFeedbackRegressionCases.Run("world site and facility labels resolve through strategic definitions", BattleHitFeedbackRegressionCases.WorldSiteAndFacilityLabelsResolveThroughDefinitions);
BattleHitFeedbackRegressionCases.Run("world action resource text uses custom resource display names", BattleHitFeedbackRegressionCases.WorldActionResourceTextUsesCustomDisplayNames);
BattleHitFeedbackRegressionCases.Run("world action site and facility preview text uses custom display names", BattleHitFeedbackRegressionCases.WorldActionSiteAndFacilityPreviewTextUsesCustomDisplayNames);
BattleHitFeedbackRegressionCases.Run("world threat auto resolve messages use configured display names", BattleHitFeedbackRegressionCases.WorldThreatAutoResolveMessagesUseConfiguredDisplayNames);
BattleHitFeedbackRegressionCases.Run("world action non-population shortage uses custom resource display name", BattleHitFeedbackRegressionCases.WorldActionNonPopulationShortageUsesCustomDisplayName);
BattleHitFeedbackRegressionCases.Run("world action blank resource display name falls back to id", BattleHitFeedbackRegressionCases.WorldActionBlankResourceDisplayNameFallsBackToId);
BattleHitFeedbackRegressionCases.Run("world opportunity reward text uses custom resource display name", BattleHitFeedbackRegressionCases.WorldOpportunityRewardTextUsesCustomResourceDisplayName);
BattleHitFeedbackRegressionCases.Run("world tick production text uses custom resource display names", BattleHitFeedbackRegressionCases.WorldTickProductionTextUsesCustomDisplayNames);
BattleHitFeedbackRegressionCases.Run("world tick threat feed uses configured display names", BattleHitFeedbackRegressionCases.WorldTickThreatFeedUsesConfiguredDisplayNames);
BattleHitFeedbackRegressionCases.Run("strategic fog stamps pixel circle independent of tile cells", BattleHitFeedbackRegressionCases.StrategicFogStampsPixelCircleIndependentOfTileCells);
BattleHitFeedbackRegressionCases.Run("strategic fog default texel stays below tile sized chunks", BattleHitFeedbackRegressionCases.StrategicFogDefaultTexelStaysBelowTileSizedChunks);
BattleHitFeedbackRegressionCases.Run("strategic fog persists explored cells while visible is derived", BattleHitFeedbackRegressionCases.StrategicFogPersistsExploredCellsWhileVisibleIsDerived);
BattleHitFeedbackRegressionCases.Run("strategic fog keeps stale site intel after leaving vision", BattleHitFeedbackRegressionCases.StrategicFogKeepsStaleSiteIntelAfterLeavingVision);
BattleHitFeedbackRegressionCases.Run("strategic navigation target lookup ignores fog visibility", BattleHitFeedbackRegressionCases.StrategicNavigationTargetLookupIgnoresFogVisibility);
BattleHitFeedbackRegressionCases.Run("strategic navigation command flow stays independent from fog", BattleHitFeedbackRegressionCases.StrategicNavigationCommandFlowStaysIndependentFromFog);
BattleHitFeedbackRegressionCases.Run("strategic navigation layer is isolated from camera transform", BattleHitFeedbackRegressionCases.StrategicNavigationLayerIsIsolatedFromCameraTransform);
BattleHitFeedbackRegressionCases.Run("strategic fog overlay uses circular visibility mask", BattleHitFeedbackRegressionCases.StrategicFogOverlayUsesCircularVisibilityMask);
BattleHitFeedbackRegressionCases.Run("world site grid exploration state persists position and memory", BattleHitFeedbackRegressionCases.WorldSiteGridExplorationStatePersistsPositionAndMemory);
BattleHitFeedbackRegressionCases.Run("world site grid exploration uses battle grid pathing outside battle turns", BattleHitFeedbackRegressionCases.WorldSiteGridExplorationUsesBattleGridPathingOutsideBattleTurns);
BattleHitFeedbackRegressionCases.Run("world site root routes authored exploration point actions", BattleHitFeedbackRegressionCases.WorldSiteRootRoutesAuthoredExplorationPointActions);
BattleHitFeedbackRegressionCases.Run("world site root gates hostile garrison text by site intel", BattleHitFeedbackRegressionCases.WorldSiteRootGatesHostileGarrisonTextBySiteIntel);
BattleHitFeedbackRegressionCases.Run("world site deployment uses known entrances before desired approach direction", BattleHitFeedbackRegressionCases.WorldSiteDeploymentUsesKnownEntrancesBeforeDesiredApproachDirection);
BattleHitFeedbackRegressionCases.Run("site exploration tick moves party by exploration AP", BattleHitFeedbackRegressionCases.SiteExplorationTickMovesPartyByExplorationAp);
BattleHitFeedbackRegressionCases.Run("site exploration tick moves patrol by route AP", BattleHitFeedbackRegressionCases.SiteExplorationTickMovesPatrolByRouteAp);
BattleHitFeedbackRegressionCases.Run("site exploration alert radius pauses simulation", BattleHitFeedbackRegressionCases.SiteExplorationAlertRadiusPausesSimulation);
BattleHitFeedbackRegressionCases.Run("world site exploration battle request carries exploration context", BattleHitFeedbackRegressionCases.WorldSiteExplorationBattleRequestCarriesExplorationContext);
BattleHitFeedbackRegressionCases.Run("exploration battle request carries patrol trigger", BattleHitFeedbackRegressionCases.ExplorationBattleRequestCarriesPatrolTrigger);
BattleHitFeedbackRegressionCases.Run("exploration battle victory removes triggering patrol", BattleHitFeedbackRegressionCases.ExplorationBattleVictoryRemovesTriggeringPatrol);
BattleHitFeedbackRegressionCases.Run("world site hover summary uses local resources and force counts", BattleHitFeedbackRegressionCases.WorldSiteHoverSummaryUsesLocalResourcesAndForceCounts);
BattleHitFeedbackRegressionCases.Run("world site hover summary stays inside viewport", BattleHitFeedbackRegressionCases.WorldSiteHoverSummaryStaysInsideViewport);
BattleHitFeedbackRegressionCases.Run("strategic world forwards middle mouse camera navigation", BattleHitFeedbackRegressionCases.StrategicWorldForwardsMiddleMouseCameraNavigation);
BattleHitFeedbackRegressionCases.Run("battle result applier messages use configured display names", BattleHitFeedbackRegressionCases.BattleResultApplierMessagesUseConfiguredDisplayNames);
BattleHitFeedbackRegressionCases.Run("battle unit factory keeps definition caches shared across scenes", BattleHitFeedbackRegressionCases.BattleUnitFactoryKeepsDefinitionCachesShared);
BattleHitFeedbackRegressionCases.Run("battle result applier uses survivor counts when garrisoning assault army", BattleHitFeedbackRegressionCases.BattleResultApplierUsesSurvivorCountsWhenGarrisoningAssaultArmy);
BattleHitFeedbackRegressionCases.Run("battle result applier keeps surviving defending garrison after defense victory", BattleHitFeedbackRegressionCases.BattleResultApplierKeepsSurvivingDefendingGarrisonAfterDefenseVictory);
BattleHitFeedbackRegressionCases.Run("unit display name translation report keeps low confidence review queue bounded", BattleHitFeedbackRegressionCases.UnitDisplayNameTranslationReportQuality);
